test - offer
grzegorz1313/portfolio pull request #1
Opened 2021-05-21 10:09 UTC by grzegorz1313

2021-05-21 10:11 UTC, wojcik92michal commented on offer.html
> +	<title>Grzegorz Sobczuk - Portfolio - offer</title>
Test

2021-05-21 10:12 UTC, wojcik92michal requested changes
No!

2021-05-21 10:12 UTC, wojcik92michal approved these changes

2021-05-21 10:12 UTC, merged

2021-05-23 21:06 UTC, grzegorz1313 commented
Znowu dużo czasu straciłem na szukanie możliwości. Nadal strona nie
wyświetla się poprawnie po wrzuceniu na ftp. Możliwe, że wina leży po
serwerze. Próbowałem to zweryfikować i znaleźć kolejny darmowy serwer, ale
tylko straciłem czas. Nie wszystkie serwery są darmowe i wiele z nimi
problemów. Nie wiem za co się zabrać. Chciałem najpierw dokończyć tą sprawę
zanim będę coś dalej robił. Nie wiem czy mam się uczyć teraz javascript,
czy próbować stworzyć nową stronę, czy dalej szukać rozwiązania.

pt., 21 maj 2021 o 12:12 Michał Wójcik ***@***.***>
napisał(a):

> ***@***.**** approved this pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/grzegorz1313/portfolio/pull/1#pullrequestreview-665307235>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUAAB2SCWEFEPR35V6DYLKLTOYW2JANCNFSM45I3CFWA>
> .
>